### ISSUE TITLE
My Gaomon M10K Pro is not detected by osu and OpenTabletDriver

### ISSUE THREAD

**Issue by MTGPROD** [OpenTabletDriver/OpenTabletDriver#1520]
## Description
When my tablet in plugged-in osu do not detect the tablet. I have installed the Open Tablet Driver and I cleaned the old Gaomon driver leftover I restarded osu pluggled the tablet in the other usb ports of my laptop but still not detected. Only Windows 10 detects it. 

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 10 Entreprise |
| OpenTabletDriver | v0.5.3.3 |
| Tablet | Gaomon M10K Pro|

**Comment by jamesbt365** [comment]
Does the tablet say its detected in the driver itself? 

If it does, but you cant use it in osu, dont run osu as admin and make sure both raw input settings are off.

If your tablet doesnt detect in otd then:
https://github.com/X9VoiD/WinUSBCleanup/releases/tag/v1.0
follow the instructions on this.

If that doesnt fix it after go ot help > export diagnosis, then save the file and send it here.

**Comment by jamesbt365** [comment]
You tablet is only supported in the pre release of otd for now, you can get it here:
https://cdn.discordapp.com/attachments/615939905566015493/890625738691211334/OpenTabletDriver.win-x64.zip

Extract this build into a folder, create a `userdata` folder inside with the other extracted files then you can run the ux. Make sure you current version of otd is closed during this.

If you want plugins in this version only a select few work at the moment. Refer to #1436 and https://github.com/AbstractQbit/AbstractOTDPlugins/actions/runs/1298122683

(Also you shouldn't use the `Administator` account because of security problems and it breaking otd and other programs)

**Comment by MTGPROD** [comment]
Okay, It's now working, thank you !
