### ISSUE TITLE
Driver thinks, that I am using a different tablet than I actually am.

### ISSUE THREAD

**Issue by XenoboticalReal** [OpenTabletDriver/OpenTabletDriver#1754]
## Description
The driver thinks, that I am using a different tablet (XP-Pen Star G540) instead of my actual tablet.

## System Information:
| Operating System: Ubuntu  21.10 x86_64 |
| OpenTabletDriver Version: v0.5.3.3 |
| Tablet: XP-Pen g430s |

**Comment by Mrcubix** [comment]
that's because these 2 tablets have the same product id and there isn't a way to differentiate them as far as i'm aware. Complain to XP-Pen (or UGEE their parent company).
Delete the G540 config, the config folder should be located in `/usr/share/OpenTabletDriver/Configurations`
You could also do the following `Tablet > Device string reader`, type the following:
- 10429
- 117
- empty

then click on dump all and upload the generated file here, tho i doubt there is any useful info as the strings are probably the same for both tablet
