### ISSUE TITLE
Setting Linux Artist Mode should set or notify of Pen Passthrough

### ISSUE THREAD

**Issue by gonX** [OpenTabletDriver/OpenTabletDriver#1767]
## Description
Right now, switching to Linux Artist mode and not setting pen passthrough for pen tip (and other relevant stylus keys) will cause odd behavior.

It's not obvious for first time users that they're required to set this manually.

Setting this to medium priority because I foresee a few users never really trying OTD because "artist mode didn't work"

**Comment by zer0exia** [comment]
This might need to be pinned (or mentioned somewhere). Veikk S640, enabling artist mode straight up made the pen tip unusable without setting the pen passthrough. 

Uninstalled & reinstalled OTB after a while (caused by arch dotnet issue). Would not be obvious for me without reading this post, because it was working fine before I uninstalled.

**Comment by InfinityGhost** [comment]
Maybe at least documented for the v0.6 release, ideally on https://opentabletdriver.net

**Comment by jamesbt365** [comment]
This should more or less notify that the tip has to be unbound, if that has to be done as if i remember correctly pen pass through was removed and instead tip has to be bound, probably wrong though.

**Comment by X9VoiD** [comment]
There's no pen passthrough anymore.
