### ISSUE TITLE
Preset files not saved with json extension are not detected during refresh

### ISSUE THREAD

**Issue by Sublimelime** [OpenTabletDriver/OpenTabletDriver#1795]
## Description

As in title, if you save a preset without including the .json extension at the end, the files are not detected by OTD when presets are refreshed.

## Reproduction:

- Save preset, do not provide extension
- Hit refresh presets, none will appear
- Rename file to "whatever.json" and hit refresh again, will detect

## Fix

I can fix this, but one of two ways:

- Detect all files in preset folder regardless of extension (may cause errors though if there's unrelated clutter there)
- Ensure files are saved with .json extension (appended if not provided by user)

Would appreciate advice, **leaning towards the second option** (as windows doesn't like extension-less files anyway, and they *are* json files so should have json extension).

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Linux (but should apply to all platforms, can't remember if windows forces extensions)
| OpenTabletDriver Version | Master (v0.6.0.0+f06a0ed6)
| Tablet                   | Irrelevant

**Comment by vedattt** [comment]
It was definitely intentional on my part to only pick up presets with json extensions, grabbing everything in the directory is just asking for trouble.

I'd say the sane option here is to just ensure that presets are saved as json's. I actually thought the file dialog would make sure to append it as default behavior, but I guess not...
