### ISSUE TITLE
no settings applied after resume from machine suspension/hybernation

### ISSUE THREAD

**Issue by OniCado** [OpenTabletDriver/OpenTabletDriver#1870]
## Description

after waking up the machine from suspension/hybernation, OTD will not send inputs unless settings are reapplied (this does not affect v0.5.3.3)
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 21H2 10 Pro N Build 19044.1415 |
| OpenTabletDriver Version | 0.6 prerelease/master |
| Tablet | --- |

**Comment by InfinityGhost** [comment]
There's no reason this should occur, nothing has changed there since v0.5.3.3. I'm unable to reproduce this.

**Comment by gonX** [comment]
Please bisect for this.

Does the tablet debugger still work when coming out of suspend?

**Comment by Sinamer** [comment]
Can confirm, I'm experiencing the same issue. After suspending and waking up my machine, tablet input not reacting to any actions. Clicking `Apply` in GUI makes it work again. This issue is not present in v0.5.3.3. Any version above it has the same behaviour.
Here's a clip of tablet debugger after a wake up (notice how the OS cursor is not moving):

https://user-images.githubusercontent.com/53346335/152315845-10215416-0770-4509-99a4-432d2e063675.mp4

**Comment by Mrcubix** [comment]
After learning a bit more about this, i think you should try one of the following:

- Enable USB > USB selective Suspend in windows advanced power settings
- Find an option in your bios to keep USB ports powered when off or suspended

**Comment by Sinamer** [comment]
Thanks for the guidance. Have tried both just now. For the former, USB selective suspend setting in power options doesn't have any effect. For the latter, there's no such USB configuration option in the UEFI for me.
I don't think it is related to the way my machine is set up, since this issue is not present in a different version of OTD.

**Comment by Mrcubix** [comment]
any OTD versions have the same issue as far as what have been reported in the past and what i'm aware of

**Comment by Sinamer** [comment]
OTD v0.5.3.3 does not show this behaviour and works after suspension. The original post also mentions that. Am I missing something?

**Comment by Mrcubix** [comment]
#552

**Comment by AkiSakurai** [comment]
https://github.com/OpenTabletDriver/OpenTabletDriver/blob/707f71ec9399056dddd8cfb6d94d0680b0b1c9f5/OpenTabletDriver.Daemon/DriverDaemon.cs#L66-L70
Is SetSettings missing here?

**Comment by vedattt** [comment]
@OniCado @Sinamer Grab an action build from #2041, see if it fixes the issue.

**Comment by Sinamer** [comment]
Yup, that fixes the issue! Thank you for looking into it!
