### ISSUE TITLE
NetSDK no longer will support -p for project.

### ISSUE THREAD

**Issue by boundingbox** [OpenTabletDriver/OpenTabletDriver#2110]
## Description
When building in Fish/Konsole, this warning appears:
Warning NETSDK1174: The abbreviation of -p for --project is deprecated. Please use --project.

Proposed solution: replace -p with --project

## System Information:
Not relevant to issue

**Comment by vedattt** [comment]
As per [NETSDK1174](https://docs.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1174), this warning should be for `dotnet run` alone, which the build scripts do not use as far as I can see. `generate-rules.sh` does though. As such, I'm assuming this happened while generating the udev rules rather than building the project.
