### ISSUE TITLE
Add support for Wacom lntuos PT S 2 (CTH-490)

### ISSUE THREAD

**Issue by kirbloz** [OpenTabletDriver/OpenTabletDriver#3346]
### Manufacturer

Wacom

### Product Name

CTH-490

### Device Width

210

### Device Height

169

### Pressure Levels

2048

### Lines per Inch (LPI)

2540

### Additional Information

Active area is 152mmx95mm

### Diagnostic Information

I dont know what to write here since the device isn't even detected

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
This tablet was supported *way way way* back in 2020.

You can see it [here](https://opentabletdriver.net/Tablets) on our list of supported tablets.

If the tablet is not detected, then see our [FAQ](https://opentabletdriver.net/Wiki/FAQ/Windows). It is impossible for me to provide any extra help with the information that I have been provided with because you didn't fill out the diagnostic information step.
![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/22662856/d6e1c7d4-89e9-4da3-9e8f-9ccd366226e6)
