### ISSUE TITLE
Failing to save configurations hard crashes

### ISSUE THREAD

**Issue by MIchael-Kelly7** [OpenTabletDriver/OpenTabletDriver#860]
## Description
Running Manjaro Linux, I was trying to add a tablet config, but everytime I try to save the program just forces closed. Even trying to click "Save configurations to" and selecting the configuration folder crashes the app.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System |  Manjaro
| Software Version |
| Tablet           | GAOMON M10K 2018

Will start a separate issue to get the config added for the tablet.

**Comment by InfinityGhost** [comment]
Is this running with the standalone release or from the AUR?

**Comment by MichaelVash7886** [comment]
@InfinityGhost The AUR. Glad to try an alternate method if you'd like me to.

**Comment by InfinityGhost** [comment]
> @InfinityGhost The AUR. Glad to try an alternate method if you'd like me to.

When you're running from the AUR, OpenTabletDriver is installed to `/usr/share/OpenTabletDriver` which is (typically) write protected from non-root users. The configuration directory is in that same directory, so trying to save there will always fail unless you run as root (which is not recommended). Will add some error message instead of hard crashing like it currently does.

**Comment by MichaelVash7886** [comment]
I wondered if that was the issue.
So it sounds like I'd need to CHOWN the `configuration` folder in `/usr/share/OpenTabletDriver` to be owned by my user then it should allow me to save normally. 
I almost wonder if a symlink to somewhere in /home would be better.
