### ISSUE TITLE
Virus detected.

### ISSUE THREAD

**Issue by dolkilu** [OpenTabletDriver/OpenTabletDriver#873]
My anti-virus (Bitdefender) says OpenTabletDriver.Daemon.exe is infected with Gen:Variant.Ulise.158901
Can I get details about this?

**Comment by Mrcubix** [comment]
Some code trigger False positive on AVs since 0.5.2, you make an exception for the daemon and you'll be good to go

**Comment by dolkilu** [comment]
thanks

**Comment by LavaDesu** [comment]
We should probably still keep this open rather than telling every user to make an exclusion.
It's been isolated to the plugin manager (specifically d52aa65)
Another note is that the binary is only flagged if it's built with sdk >5.0.2, building it on 5.0.1 can be a temporary solution for future releases.
